import {
  BarChartOutline,
  BrushOutline,
  CameraOutline,
  ChatbubbleOutline,
  CloudOutline,
  FlagOutline,
  GlobeOutline,
  HeartOutline,
  HomeOutline,
  LockClosedOutline,
  LogoFacebook,
  LogoInstagram,
  MailOutline,
  MapOutline,
  NotificationsOutline,
  PersonOutline,
  PhonePortraitOutline,
  PlayOutline,
  RefreshOutline,
  SaveOutline,
  SearchOutline,
  SendOutline,
  SettingsOutline,
  ShareOutline,
  StarOutline,
  TrashOutline,
  WarningOutline,
} from "react-ionicons";

const iconMap: Record<
  string,
  React.FC<{ color?: string; width?: string; height?: string }>
> = {
  flag: FlagOutline,
  "bar-chart": BarChartOutline,
  "paint-brush": BrushOutline,
  "logo-instagram": LogoInstagram,
  "logo-facebook": LogoFacebook,
  home: HomeOutline,
  settings: SettingsOutline,
  search: SearchOutline,
  heart: HeartOutline,
  star: StarOutline,
  camera: CameraOutline,
  chatbubble: ChatbubbleOutline,
  cloud: CloudOutline,
  globe: GlobeOutline,
  "lock-closed": LockClosedOutline,
  mail: MailOutline,
  map: MapOutline,
  notifications: NotificationsOutline,
  person: PersonOutline,
  "phone-portrait": PhonePortraitOutline,
  play: PlayOutline,
  refresh: RefreshOutline,
  save: SaveOutline,
  send: SendOutline,
  share: ShareOutline,
  trash: TrashOutline,
  warning: WarningOutline,
};

export default iconMap;
